services:
  presentation:
    build: 
      context: ./presentation
      dockerfile: Dockerfile
    ports:
      - "3000:5173"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
      - FAST_REFRESH=false
      - WDS_SOCKET_PORT=3000
    volumes:
      - ./presentation/src:/usr/src/app/src
    networks:
      - 4layers_network
  business_logic:
    build: 
      context: ./business_logic
      dockerfile: Dockerfile
    ports:
      - "4000:3000"
    volumes:
      - ./business_logic/src:/usr/src/app/src
    networks:
      - 4layers_network
  services:
    build: 
      context: ./services
      dockerfile: Dockerfile
    ports:
      - "5000:3000"
    volumes:
      - ./services/src:/usr/src/app/src
    networks:
      - 4layers_network
  data_access:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: university
    volumes:
      - ./data:/data
      - ./scripts:/docker-entrypoint-initdb.d
    networks:
      - 4layers_network
networks:
  4layers_network:
    driver: bridge